---
title       : R, the solution to (almost) all of your life's problems
subtitle    : 
author      : Nathaniel Phillips, University of Basel
job         : PsyKo 2017, Bern
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---


## Goal of this workshop

- Get you excited about learning R!
- You won't become a master of R today unfortunately, not enough time

--- .class #id 

## My R Journey

1. 5 years struggling with SPSS
2. 5 years of glorious R.

--- .class #id 

## Why is R so great?

1. Free and open source
2. Replication and Sharing
3. Statistics (duh)
4. Plotting
5. Simulations
6. Writing APA style documents
7. Contributing to the R community
8. Bonuses!!

--- .class #id 

## Free and open source

--- .class #id 

## Replication

--- .class #id 

## Sharing

--- .class #id 

## Statistics

--- .class #id 

## Plotting

- Graphics are like designer cars, when it's made by a great manufacturer (like R), you can see it. When it's made cheaply, (like SPSS), you can see that too.

1. SPSS Barplot vs. R pirateplot
2. SPSS scatterplot vs R scatterplot
3. R network plot
4. Fun plots: balloon plot


--- .class #id 

## Simulations

--- .class #id 

## Writing APA papers with papaja

--- .class #id 

## Bonuses!

1. Create Markdown documents
2. Create HTML presentations (like this one!) with `slidify`
3. Show interactive data and write experiments with Shiny
4. Contribute to R by creating your own R packages

--- .class #id 
## R has a learning curve

1. Switching from SPSS to R is not like switching from one car brand to another, it's like switching from buying pre-made cars to learning how to build your own.
2. Compare two people at the start of their PhD, one uses SPSS, the other uses R.


--- .class #id 
## Practical tutorial

- Loading data.
- Descriptive statistics
- Plotting
- T-tests, correlation tests
- ANOVA
- Regression
- Simulations
- APA style papers with papaja

--- .class #id 
## I am ready to learn more R! What can I do?

| Book | Author | WebLink |
|:------|:------|:------|
| YaRrr! The Pirate's Guide to R|Me | [www.thepiratesguidetor.com](www.thepiratesguidetor.com) |
| R for Data Science|Wickham & Grolemund | [http://r4ds.had.co.nz/](http://r4ds.had.co.nz/)
| The R book | Crawley | [https://www.amazon.com/R-Book-Michael-J-Crawley/dp/0470973927](https://www.amazon.com/R-Book-Michael-J-Crawley/dp/0470973927) |
| Discovering Statistics using R | Field & Miles | [https://www.amazon.com/Discovering-Statistics-Using-Andy-Field/dp/1446200469/](https://www.amazon.com/Discovering-Statistics-Using-Andy-Field/dp/1446200469/) |

<br>

| Course | Link |
|:------|:------|
|Coursera|[https://www.coursera.org/courses?query=R](https://www.coursera.org/courses?query=R) |
|DataCamp |[https://www.datacamp.com/courses/free-introduction-to-r](https://www.datacamp.com/courses/free-introduction-to-r)|

#### Social Media
- www.r-bloggers.com, Facebook: R Users Psychology
